# Generated by Django 5.2.15 on 2026-06-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('service_type', models.CharField(choices=[('general', 'General'), ('specialist', 'Specialist'), ('followup', 'Follow Up')], default='general', max_length=20)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('token_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('serving', 'Serving'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('estimated_wait', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
