# Generated by Django 5.2.15 on 2026-06-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_queueconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reschedule_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
