# Generated by Django 5.2.15 on 2026-06-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_reschedule_suggested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('general', 'General'), ('specialist', 'Specialist'), ('followup', 'Follow Up'), ('dental', 'Dental'), ('banking', 'Banking'), ('government', 'Government')], default='general', max_length=20),
        ),
    ]
